# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.CharField(default='Peasant', max_length=200),
        ),
    ]
