# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_admin', '0004_passwordmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordManager',
        ),
    ]
